_target_: mettagrid.map.mapgen.MapGen

width: ${uniform:20,80,40}
height: ${uniform:20,80,40}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.terraingen.TerrainGen
      layers:
      - fn : mettagrid.map.scenes.terraingen.fn7
        saturation: ${choose:1,2,3,4}
      - fn : mettagrid.map.scenes.terraingen.fn6
        saturation: 0


      cutoff: ${uniform:5,160}                  #cutoff treshold
      sampling_params:  
        lx: ${uniform:0.05,0.2}                 #scaling along x
        ly: ${uniform:0.05,0.2}                 #scaling along y
        t: ${uniform:0,1}                       #additional rotation in 2*pi radians
        symmetry: ${choose:1,2,3,4,5,6,7,8}     #symmetry type
        xc: ${uniform:-0.7,0.7}                 #x off-center
        yc: ${uniform:-0.7,0.7}                 #y off-center

