_target_: mettagrid.map.mapgen.MapGen

width: ${uniform:20,80,40}
height: ${uniform:20,80,40}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      layers:
      - fn : mettagrid.map.scenes.simplex_sampler.fn7   # radial symmetry
        saturation: ${choose:1,2,3,4}
        params:
          lx: ${uniform:0.05,0.2}                       # scaling along x
          ly: ${uniform:0.05,0.2}                       # scaling along y
          t: ${uniform:0,1}                             # additional rotation in 2*pi radians
          symmetry: ${choose:1,2,3,4,5,6,7,8}           # symmetry type
          xc: ${triangular:-0.7,0.0,0.7}                # x off-center
          yc: ${triangular:-0.7,0.0,0.7}                # y off-center
      - fn : mettagrid.map.scenes.simplex_sampler.fn0   # random noise
        saturation: ${uniform:0.0,0.5}
        params:
          lx: ${uniform:0.01,0.5}                       # scaling along x
          ly: ${uniform:0.01,0.5}                       # scaling along y

      cutoff: ${uniform:5,160}                          # cutoff treshold less number -> less walls

