_target_: mettagrid.map.mapgen.MapGen

width: ${uniform:20,80,40}
height: ${uniform:20,80,40}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      layers:
      - fn : mettagrid.map.scenes.simplex_sampler.fn9     # lattice-like terrain
        saturation: ${choose:1.9,2.0,2.1,2.2,2.3,2.4,2.5,3.0,4.0}
        params:
          lx: ${uniform:1,3}                              # scaling along x
          ly: ${uniform:1,3}                              # scaling along y
          ox: ${choose:2,3,4,5,6,7,8,9,10,11,12,13,14,15} # amplitude of walls along x
          oy: ${choose:2,3,4,5,6,7,8,9,10,11,12,13,14,15} # amplitude of walls along y
          px: ${choose:0,1}                               # thickness of x walls
          py: ${choose:0,1}                               # thickness of y walls
      - fn : mettagrid.map.scenes.simplex_sampler.fn0     # random noise
        saturation: 0 #${uniform:0.0,1.5}                 # currently at 0 to avoid noise breaking the lattice too much
        params:
          lx: ${uniform:0.01,0.5}                         # scaling along x
          ly: ${uniform:0.01,0.5}                         # scaling along y

      cutoff: ${uniform:50,90}                            # cutoff treshold less number -> less walls

  # - where: full
  #   scene:
  #       _target_: mettagrid.map.scenes.make_connected.MakeConnected


