_target_: mettagrid.map.mapgen.MapGen

width: ${int:${uniform:20,101}}
height: ${int:${uniform:20,101}}

root:
  _target_: mettagrid.map.scenes.room_grid.RoomGrid
  rows: 3
  columns: 3

  children:
  - scene:
      _target_: mettagrid.map.scenes.simplex_sampler.SimplexSampler
      layers:
      - sampling_function : mettagrid.map.scenes.simsam_functions.arbitrary_tilted_napkin     # tilted napkin-like terrain
        saturation: ${choose:1.9,2.0,2.1,2.2,2.3,2.4,2.5,3.0,4.0}
        function_parameters:
          x_zoom: ${uniform:1,3}                                                # scaling along x
          y_zoom: ${uniform:1,3}                                                # scaling along y
          angle_theta: 0.125                                                    # angle theta in 2pi radians: 0.25 is 90degrees, 0.125 is 45deg
          line1_wavelength: ${int:${uniform:2,16}}                              # wavelength of walls along line1 (x+y)
          line2_wavelength: ${int:${uniform:2,16}}                              # wavelength of walls along line2 (x-y)
          line1_thickness: ${choose:1,2}                                        # thickness of line1 walls (x+y)
          line2_thickness: ${choose:1,2}                                        # thickness of line2 walls (x-y)
      - sampling_function : mettagrid.map.scenes.simsam_functions.xy_noise     # random noise
        saturation: 0 #${uniform:0.0,1.5}                 # currently at 0 to avoid noise breaking the lattice too much
        function_parameters:
          x_zoom: ${uniform:0.01,0.5}                         # scaling along x
          y_zoom: ${uniform:0.01,0.5}                         # scaling along y

      cutoff: ${uniform:50,90}                            # global cutoff threshold less number -> less walls
      force_seed: 0 # 0 will use random seeds, any other integer will force the seed. Requires all above parameters to be fixed to produce identical results


